name: DeepThinker
description: A deep thinker agent that helps me think deeply about a topic or problem.
temperature: 0.3
max_tokens: 8192
class: agent_core.agents.openai_base_agent.OpenAIAgent
base_url: http://localhost:1337/v1
api_key: local_api_key
model: gpt-oss-20b-mlx-8bit

